# Generated by Django 6.0 on 2026-01-06 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_payment_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='plan',
            field=models.CharField(choices=[('FREE', 'Gratuit'), ('STARTER', 'Basique'), ('PRO', 'Intermédiaire'), ('PREMIUM', 'Premium')], default='FREE', max_length=30),
        ),
    ]
