# Generated by Django 6.0 on 2026-01-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_payment_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collecte',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
