# Generated by Django 6.0 on 2026-01-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_collecte_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collecte',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
