# Generated by Django 6.0 on 2026-01-08 20:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_collecte_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='collecte',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
